name = "ObaraSaika"
uuid = "5b212b89-b4cd-42cd-a3f8-ba7ab2c3d492"
authors = ["Eric Berquist <eric.berquist@gmail.com> and contributors"]
version = "0.1.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"

[compat]
GSL = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
